spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/IdeaProjects/JPA/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  output:
    ansi:
      enabled: never
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql : true
        format_sql : true
        default_batch_fetch_size : 100
    generate-ddl: true

logging:
  level:
    root : info
    org.hibernate.SQL : debug
#    org.hibernate.type : trace
  file: myApp.log


